FROM anyscale/ray:2.56.0-slim-py312-cu128

RUN sudo apt-get update -y && sudo apt-get install -y wget kmod libxml2 build-essential libnuma-dev

# the cuda compiler here is needed for deepspeed
RUN wget https://developer.download.nvidia.com/compute/cuda/12.8.0/local_installers/cuda_12.8.0_570.86.10_linux.run \
    && sudo sh cuda_12.8.0_570.86.10_linux.run --silent --toolkit && rm -rf cuda_12.8.0_570.86.10_linux.run

RUN curl -LsSf https://astral.sh/uv/0.9.4/install.sh | sh
RUN echo "export RAY_RUNTIME_ENV_HOOK=ray._private.runtime_env.uv_runtime_env_hook.hook" >> /home/ray/.bashrc


RUN sudo apt-get update \
    && sudo apt-get install -y openssh-server iputils-ping net-tools iproute2 traceroute netcat \
    libopenexr-dev libxi-dev libglfw3-dev libglew-dev libomp-dev libxinerama-dev libxcursor-dev tzdata \
    && sudo apt-get clean && sudo rm -rf /var/lib/apt/lists/*

RUN sudo apt update && sudo apt install --fix-broken && sudo apt install -y default-jre-headless openjdk-8-jdk \
    && sudo apt-get clean \
    && sudo rm -rf /var/lib/apt/lists/*

# build toolchain + nccl dev headers for transformer engine build
RUN sudo apt-get update && sudo apt-get install -y \
    cmake \
    ninja-build \
    libnccl-dev=2.25.1-1+cuda12.8 \
    libnccl2=2.25.1-1+cuda12.8 \
    && sudo apt-get clean && sudo rm -rf /var/lib/apt/lists/*

# ---------- PyTorch + cuDNN (setup for transformer-engine) ----------
# PyTorch + cuDNN
RUN uv pip install --system --no-cache-dir "torch==2.11.0" "nvidia-cudnn-cu12>=9.3" && \
    CUDNN_PATH="$(python -c 'import nvidia.cudnn as c; print(c.__path__[0])')" && \
    sudo mkdir -p /opt && sudo ln -sfn "$CUDNN_PATH" /opt/cudnn && \
    echo "/opt/cudnn/lib" | sudo tee /etc/ld.so.conf.d/cudnn.conf >/dev/null && sudo ldconfig

ENV CUDNN_PATH=/opt/cudnn
ENV CPATH=${CUDNN_PATH}/include:${CPATH}
ENV LD_LIBRARY_PATH=${CUDNN_PATH}/lib:${LD_LIBRARY_PATH}

RUN uv pip install  --system --no-cache-dir \
    nvidia-mathdx \
    pybind11 \
    setuptools \
    wheel

ENV CMAKE_ARGS=-DPython_EXECUTABLE=/home/ray/anaconda3/bin/python3
# --------------------